# Generated by Django 4.2 on 2025-06-14 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0009_blockeduser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockeduser",
            options={},
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="blocked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
