# Generated by Django 4.2 on 2025-06-13 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0010_bookdiscussion_discussionreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdiscussion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='pybo.book'),
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='pybo.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pybo_borrow_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
