# Generated by Django 4.2 on 2025-06-14 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0011_alter_blockeduser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="bookmark_users",
            field=models.ManyToManyField(
                related_name="bookmark_question", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
