# Generated by Django 4.2 on 2025-06-14 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0013_userpreference_created_at_alter_userpreference_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="created_at",
        ),
    ]
