# Generated by Django 4.2 on 2025-06-15 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0014_remove_userpreference_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="bookmark_users",
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
